# Is only example for build docker image and pushed to storage when test was complete
# You can change it as you want

name: Build & Push Docker Image

on:
  workflow_run:
    workflows: ["Bun Test & Typecheck"]
    types:
      - completed
    branches:
      - main

jobs:
  build-and-push:
    # Run only if the triggering workflow succeeded and it was for the main branch
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch == 'main' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.SECRET_TOKEN }}

      - name: Extract Docker metadata (tags, labels)
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=sha
            # publish latest only for main
            type=raw,value=latest,enable=${{ github.event.workflow_run.head_branch == 'main' }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./ci/dockerfile/backend-service.dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
