name: Bun Test & Typecheck

on:
  push:
  pull_request:

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    env:
      DB_HOST: ${{ secrets.DB_HOST != '' && secrets.DB_HOST || 'localhost' }}
      DB_PORT: ${{ secrets.DB_PORT != '' && secrets.DB_PORT || '5432' }}
      DB_USER: ${{ secrets.DB_USER != '' && secrets.DB_USER || 'postgres' }}
      DB_PWD:  ${{ secrets.DB_PWD  != '' && secrets.DB_PWD  || 'postgres' }}
      DB_NAME: ${{ secrets.DB_NAME != '' && secrets.DB_NAME || 'postgres' }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Run type check
        run: bun run typecheck

      - name: Run tests
        run: bun test
